#!/usr/bin/env python3
"""Test client for the VoxCPM API server.

Usage:
  python tests/test_api.py                          # all modes against default base url
  python tests/test_api.py --base-url https://...    # custom base url
  python tests/test_api.py --ref path/to/voice.wav   # enable cloning tests
"""

import argparse
import base64
import json
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path
from typing import Optional

DEFAULT_BASE_URL = "https://u135655-3kfe-35e0a805.bjb2.seetacloud.com:8443"


def _request(base_url: str, method: str, path: str, payload=None, timeout: int = 600):
    url = base_url.rstrip("/") + path
    data = None
    headers = {"Accept": "application/json"}
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8", errors="replace")
            return resp.status, body
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        return exc.code, body
    except urllib.error.URLError as exc:
        return -1, f"URLError: {exc}"


def _decode_audio_b64(b64_str: str) -> bytes:
    s = b64_str.strip()
    if s.startswith("data:"):
        s = s.split(",", 1)[1] if "," in s else s
    return base64.b64decode(s)


def _read_audio_b64(path: str) -> str:
    data = Path(path).read_bytes()
    return "data:audio/wav;base64," + base64.b64encode(data).decode("ascii")


def test_health(base_url: str):
    print("\n=== [1] GET /api/health ===")
    status, body = _request(base_url, "GET", "/api/health", timeout=30)
    print(f"status={status}")
    print(body)
    return status == 200


def test_status(base_url: str):
    print("\n=== [2] GET /api/voxcpm/status ===")
    status, body = _request(base_url, "GET", "/api/voxcpm/status", timeout=30)
    print(f"status={status}")
    print(body)
    return status == 200


def test_unload(base_url: str):
    print("\n=== [3] POST /api/voxcpm/unload ===")
    status, body = _request(base_url, "POST", "/api/voxcpm/unload", payload={}, timeout=60)
    print(f"status={status}")
    print(body)
    return status == 200


def _save_audio(resp_json: dict, tag: str, out_dir: Path) -> Optional[Path]:
    if not resp_json.get("ok") or not resp_json.get("audio_base64"):
        print(f"  [!] no audio in response for {tag}")
        return None
    audio_bytes = _decode_audio_b64(resp_json["audio_base64"])
    out_path = out_dir / f"{tag}.wav"
    out_path.write_bytes(audio_bytes)
    print(f"  saved: {out_path} ({len(audio_bytes)} bytes)")
    return out_path


def test_synthesize(base_url: str, out_dir: Path, ref_path: Optional[str]):
    ok_all = True

    # --- 4a. Voice Design (no reference audio) ---
    print("\n=== [4a] POST /api/voxcpm/synthesize — Voice Design ===")
    payload = {
        "text": "Hello, welcome to VoxCPM2! This is a voice design test.",
        "control_instruction": "A young woman, gentle and sweet voice",
        "cfg_value": 2.0,
        "inference_timesteps": 10,
    }
    t0 = time.time()
    status, body = _request(base_url, "POST", "/api/voxcpm/synthesize", payload=payload)
    dt = time.time() - t0
    print(f"status={status} elapsed={dt:.2f}s")
    try:
        j = json.loads(body)
    except Exception:
        print(body)
        ok_all = False
    else:
        print(json.dumps({k: v for k, v in j.items() if k != "audio_base64"}, ensure_ascii=False, indent=2))
        ok_all = ok_all and j.get("ok", False)
        _save_audio(j, "voice_design", out_dir)

    # --- 4b. Default TTS (only text) ---
    print("\n=== [4b] POST /api/voxcpm/synthesize — Default TTS ===")
    payload = {
        "text": "VoxCPM2 is a tokenizer-free text-to-speech system.",
        "cfg_value": 2.0,
        "inference_timesteps": 10,
    }
    t0 = time.time()
    status, body = _request(base_url, "POST", "/api/voxcpm/synthesize", payload=payload)
    dt = time.time() - t0
    print(f"status={status} elapsed={dt:.2f}s")
    try:
        j = json.loads(body)
    except Exception:
        print(body)
        ok_all = False
    else:
        print(json.dumps({k: v for k, v in j.items() if k != "audio_base64"}, ensure_ascii=False, indent=2))
        ok_all = ok_all and j.get("ok", False)
        _save_audio(j, "default_tts", out_dir)

    # --- 4c. Controllable Cloning (reference audio) ---
    if ref_path and Path(ref_path).exists():
        print("\n=== [4c] POST /api/voxcpm/synthesize — Controllable Cloning ===")
        payload = {
            "text": "This is a cloned voice generated by VoxCPM2.",
            "reference_audio_base64": _read_audio_b64(ref_path),
            "control_instruction": "slightly faster, cheerful tone",
            "cfg_value": 2.0,
            "inference_timesteps": 10,
            "denoise": True,
        }
        t0 = time.time()
        status, body = _request(base_url, "POST", "/api/voxcpm/synthesize", payload=payload)
        dt = time.time() - t0
        print(f"status={status} elapsed={dt:.2f}s")
        try:
            j = json.loads(body)
        except Exception:
            print(body)
            ok_all = False
        else:
            print(json.dumps({k: v for k, v in j.items() if k != "audio_base64"}, ensure_ascii=False, indent=2))
            ok_all = ok_all and j.get("ok", False)
            _save_audio(j, "controllable_clone", out_dir)

        # --- 4d. Ultimate Cloning (prompt_wav + prompt_text) ---
        print("\n=== [4d] POST /api/voxcpm/synthesize — Ultimate Cloning ===")
        payload = {
            "text": "This is an ultimate cloning demonstration using VoxCPM2.",
            "prompt_wav_base64": _read_audio_b64(ref_path),
            "prompt_text": "The transcript of the reference audio.",
            "reference_audio_base64": _read_audio_b64(ref_path),
            "cfg_value": 2.0,
            "inference_timesteps": 10,
        }
        t0 = time.time()
        status, body = _request(base_url, "POST", "/api/voxcpm/synthesize", payload=payload)
        dt = time.time() - t0
        print(f"status={status} elapsed={dt:.2f}s")
        try:
            j = json.loads(body)
        except Exception:
            print(body)
            ok_all = False
        else:
            print(json.dumps({k: v for k, v in j.items() if k != "audio_base64"}, ensure_ascii=False, indent=2))
            ok_all = ok_all and j.get("ok", False)
            _save_audio(j, "ultimate_clone", out_dir)
    else:
        print("\n(skip cloning tests: no --ref provided)")

    return ok_all


def main(argv=None):
    parser = argparse.ArgumentParser(description="VoxCPM API test client")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help="API base URL")
    parser.add_argument("--ref", default=None, help="reference audio path for cloning tests")
    parser.add_argument("--out-dir", default="test_api_outputs", help="directory to save outputs")
    parser.add_argument("--skip-unload", action="store_true", help="skip the unload test")
    args = parser.parse_args(argv)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    base_url = args.base_url

    # Use an unverified SSL context by default — self-signed certs on some
    # cloud endpoints will otherwise fail. Uncomment the override below if
    # the endpoint has a valid cert and you want verification.
    import ssl
    ssl._create_default_https_context = ssl._create_unverified_context

    results = []
    results.append(("health", test_health(base_url)))
    results.append(("status", test_status(base_url)))
    results.append(("synthesize", test_synthesize(base_url, out_dir, args.ref)))
    if not args.skip_unload:
        results.append(("unload", test_unload(base_url)))

    print("\n=== Summary ===")
    all_ok = True
    for name, ok in results:
        print(f"  {name}: {'PASS' if ok else 'FAIL'}")
        all_ok = all_ok and ok
    print(f"\nOverall: {'ALL PASS' if all_ok else 'SOME FAILED'}")
    print(f"Outputs saved to: {out_dir.resolve()}")
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
